import type { NextPage } from 'next'
import Head from 'next/head'
import classes from './index.module.scss'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>NFT Marketplace</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={classes.root}>
        <h1>Today's Trending</h1>
        <div className={classes.grid}>
          <div className={classes.box}></div>
          <div className={classes.box}></div>
          <div className={classes.box}></div>
          <div className={classes.box}></div>
          <div className={classes.box}></div>
          <div className={classes.box}></div>
        </div>
      </div>
    </>
  )
}

export default Home
